// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Our Story"
          title="Authentic Italian Hospitality"
          description="Tuto Restaurant is a family-run gem in E17. We pride ourselves on using locally sourced ingredients alongside the finest Italian imports to craft dishes that honor our heritage."
          imageSrc="http://img.b2bpic.net/free-photo/surface-with-different-foodstuffs_23-2147612075.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
