// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Ready to Visit?"
          text="Call us today to reserve your table and enjoy the finest Italian dining in Walthamstow."
          primaryButton={{
            text: "Call Now",
            href: "tel:02081497688",
          }}
          secondaryButton={{
            text: "Get Directions",
            href: "https://maps.app.goo.gl/deDepYPcpYD5o9nt7",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
