// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Common Questions"
          title="Everything You Need to Know"
          description="Have questions about your visit? Here are the most frequently asked questions."
          items={[
            {
              question: "Do I need to book in advance?",
              answer: "We strongly recommend booking in advance, especially for weekend evenings.",
            },
            {
              question: "Where are you located?",
              answer: "Find us at 110 Wood St, London E17 3HX.",
            },
            {
              question: "Do you offer vegetarian options?",
              answer: "Yes, we have a variety of delicious vegetarian dishes on our menu.",
            },
            {
              question: "Can I bring my family?",
              answer: "Absolutely! We welcome families and provide a warm environment for all.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/close-up-crystal-glasses_1203-631.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
