// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroTiltedCards from '@/components/sections/hero/HeroTiltedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroTiltedCards
          tag="Authentic Cuisine"
          title="Experience Italy in London"
          description="Tuto Restaurant brings the traditional flavors of Italy to 110 Wood Street. Join us for a culinary journey of passion and quality."
          primaryButton={{
            text: "Call to Book",
            href: "tel:02081497688",
          }}
          secondaryButton={{
            text: "See Menu",
            href: "#menu",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/wedding-reception-room-with-decorated-table-setting-sea-view-through-window_637285-984.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-man-putting-mozzarella-baked-pizza-dough-with-smoked-salmon-slices_23-2148785701.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-delicious-sandwiches-with-tomatoes-olives-inside-plate-white-background-toast-bread-lunch-burger-horizontal-meal-food_140725-158810.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/spaghetti-with-mussels-bell-peppers-served-with-white-wine_140725-8468.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-tasty-meatballs-soup-with-vegetables-dark-table-sauce-dish-colors_140725-81719.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
