// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroTiltedCards from '@/components/sections/hero/HeroTiltedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroTiltedCards
          tag="Authentic Cuisine"
          title="Experience Italy in London"
          description="Tuto Restaurant brings the traditional flavors of Italy to 110 Wood Street. Join us for a culinary journey of passion and quality."
          primaryButton={{
            text: "Call to Book",
            href: "tel:02081497688",
          }}
          secondaryButton={{
            text: "See Menu",
            href: "#menu",
          }}
          items={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1789654426063-cjdhwluo.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1789654358358-ny52uhwe.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1789654370059-x7hyct3i.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1789654381015-p53vyc07.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1789654387883-vg83df3c.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
