// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "menu" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MenuSection(): React.JSX.Element {
  return (
    <div id="menu" data-section="menu">
        <SectionErrorBoundary name="menu">
              <FeaturesRevealCardsBento
          tag="From the Kitchen"
          title="Our Signature Flavors"
          description="Explore our curated selection of classic Italian dishes."
          items={[
            {
              title: "Homemade Pasta",
              description: "Freshly prepared daily with traditional techniques.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/baking-delicious-pizza-with-wood-fired-oven_23-2150134278.jpg",
            },
            {
              title: "Wood-Fired Pizza",
              description: "Crispy base, authentic toppings, perfection.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/salad-with-tomato-cheese-slices_140725-2835.jpg",
            },
            {
              title: "Seafood Special",
              description: "Fresh catch prepared in the Mediterranean style.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/red-wine-carafe-glass-table_23-2149706791.jpg",
            },
            {
              title: "Antipasti Platter",
              description: "Perfect selection to start your dining journey.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/minestrone-soup-pan-light-table-top-view-italian-soup-with-pasta-seasonal-vegetables-delicious-vegetarian-food-concept_127032-2696.jpg",
            },
            {
              title: "Classic Risotto",
              description: "Creamy, flavorful, and cooked to perfection.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/plate-with-delicious-italian-pasta-dish_23-2149460134.jpg",
            },
            {
              title: "Tiramisu",
              description: "Our signature Italian dessert ender.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/healthy-mexican-salad_23-2148140257.jpg",
            },
            {
              title: "Fine Wines",
              description: "Curated selection from Italian regions.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/cast-iron-pan-mussels-cream-sauce-garnished-with-fresh-herbs_140725-1442.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
