// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "menu" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MenuSection(): React.JSX.Element {
  return (
    <div id="menu" data-section="menu">
        <SectionErrorBoundary name="menu">
              <FeaturesRevealCardsBento
          tag="From the Kitchen"
          title="Our Signature Flavors"
          description="Explore our curated selection of classic Italian dishes."
          items={[
            {
              title: "Homemade Pasta",
              description: "Freshly prepared daily with traditional techniques.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/27866922/pexels-photo-27866922.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=27866922",
            },
            {
              title: "Wood-Fired Pizza",
              description: "Crispy base, authentic toppings, perfection.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/6223172/pexels-photo-6223172.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=6223172",
            },
            {
              title: "Seafood Special",
              description: "Fresh catch prepared in the Mediterranean style.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/32966718/pexels-photo-32966718.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=32966718",
            },
            {
              title: "Antipasti Platter",
              description: "Perfect selection to start your dining journey.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/5975429/pexels-photo-5975429.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=5975429",
            },
            {
              title: "Classic Risotto",
              description: "Creamy, flavorful, and cooked to perfection.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/plate-with-delicious-italian-pasta-dish_23-2149460134.jpg",
            },
            {
              title: "Tiramisu",
              description: "Our signature Italian dessert ender.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/27219786/pexels-photo-27219786.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=27219786",
            },
            {
              title: "Fine Wines",
              description: "Curated selection from Italian regions.",
              href: "#",
              imageSrc: "https://images.pexels.com/photos/16053261/pexels-photo-16053261.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=16053261",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
