// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Our Excellence"
          title="Rated Among the Best"
          description="Our dedication to quality has earned us a prestigious 4.8-star rating from our wonderful diners."
          metrics={[
            {
              value: "4.8",
              title: "Google Rating",
              features: [
                "Over 100+ Reviews",
                "Top Rated Quality",
                "Authentic Experience",
              ],
            },
            {
              value: "Wood St.
    ",
              title: "Location",
              features: [
                "Wood St.
     Wood St, London",
                "E17 3HX",
                "Easy Access",
              ],
            },
            {
              value: "0208",
              title: "Contact",
              features: [
                "Call for Reservations",
                "Daily Support",
                "Open Hours Available",
              ],
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
