// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
          tag="Diner Reviews"
          title="Words from our Customers"
          description="Join our community of happy diners who love the Tuto experience."
          testimonials={[
            {
              name: "Mother ofboys",
              role: "Foodie",
              quote: "My best friend and I visited this beautiful Italian restaurant whilst on a business trip to London, and honestly it was one of the highlights of our trip.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1790072683524-leelj267.png",
            },
            {
              name: "Julie",
              role: "Local Guide",
              quote: "Last minute Mothers day treat, have not been here before but will definitely return.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1790072276479-j2l3unqf.png",
            },
            {
              name: "Thomas G.
",
              role: "Diner",
              quote: "Absolutely amazing experience at Tuto today! ❤️",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLscP9beQHn8gWQw9DRufBbp25/uploaded-1790072530033-72wvdher.png",
            },
            {
              name: "David R.",
              role: "Guest",
              quote: "The 4.8 rating is well deserved. Everything from appetizer to dessert was flawless.",
              imageSrc: "http://img.b2bpic.net/free-photo/enthusiastic-asian-female-entrepreneur-cafe-owner-with-tablet-wearing-shop-uniform-standing-with_1258-197423.jpg",
            },
            {
              name: "Claire P.",
              role: "Frequent Diner",
              quote: "The staff are so friendly and the quality of ingredients really shines through.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-man-dinner_23-2148060594.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
