// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
          tag="Diner Reviews"
          title="Words from our Customers"
          description="Join our community of happy diners who love the Tuto experience."
          testimonials={[
            {
              name: "Viorica Feraru",
              role: "Foodie",
              quote: "We ordered a couple of pasta dishes, a big pizza, and a mixed fried platter—and everything was absolutely delicious.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-portrait-beautiful-black-skinned-woman-wearing-blouse-flower-headband-enjoying-dinner-while-eating-restaurant_613910-5658.jpg",
            },
            {
              name: "Julie",
              role: "Local Guide Guide",
              quote: "Last minute Mothers day treat, have not been here before but will definitely return.",
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-male-courier-yellow-uniform-cape-with-round-delivery-bowl-his-hands-pink-background_140725-40591.jpg",
            },
            {
              name: "Elena V.",
              role: "Diner",
              quote: "A truly authentic atmosphere. Felt like I was back in Rome for a few hours.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-handsome-asian-man-friends-reunion_23-2149244687.jpg",
            },
            {
              name: "David R.",
              role: "Guest",
              quote: "The 4.8 rating is well deserved. Everything from appetizer to dessert was flawless.",
              imageSrc: "http://img.b2bpic.net/free-photo/enthusiastic-asian-female-entrepreneur-cafe-owner-with-tablet-wearing-shop-uniform-standing-with_1258-197423.jpg",
            },
            {
              name: "Claire P.",
              role: "Frequent Diner",
              quote: "The staff are so friendly and the quality of ingredients really shines through.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-man-dinner_23-2148060594.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
